# Generated by Django 3.2.3 on 2021-08-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=100)),
                ('Type', models.CharField(blank=True, max_length=50)),
                ('Language', models.CharField(max_length=100)),
                ('Summary', models.CharField(max_length=500)),
                ('Total_copies', models.CharField(max_length=100)),
                ('Available_copies', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(max_length=800),
        ),
    ]
