# Generated by Django 3.2.3 on 2021-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210826_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Available_copies',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='Total_copies',
            field=models.CharField(max_length=50),
        ),
    ]
